### ISSUE TITLE
Output of JBake compilation is incorrect

### ISSUE THREAD

**Issue by hmf** [lefou/mill-jbake#11]
I was trying to serve the site using the following command:

```
~/VSCodeProjects/hashnode-pubs$ ./mill -i site.jbakeServe
```

Unfortunately that will fail because JBake serving expects the site to be in an `output` directory. In my case the `jbake` command placed the  compile site into: 

```
/home/hmf/VSCodeProjects/hashnode-pubs/out/site/jbake.dest
```

But as the output below shows, serving requires the output to be in: 

```
/hmf/VSCodeProjects/hashnode-pubs/out/site/jbake.dest/output
```

Here is the output:

```
[8/8] site.jbakeServe 
JBake v2.6.7 (2021-05-14 21:54:29[GMT+01:00]) [http://jbake.org]

18:19:47.956 INFO  org.jbake.launcher.BakeWatcher - Watching for (content, template, asset) changes in [/home/hmf/VSCodeProjects/hashnode-pubs/out/site/jbake.dest]
18:19:48.025 INFO  org.jbake.launcher.JettyServer - Serving out contents of: [/home/hmf/VSCodeProjects/hashnode-pubs/out/site/jbake.dest/output] on http://localhost:8820/
18:19:48.025 INFO  org.jbake.launcher.JettyServer - (To stop server hit CTRL-C)
```

The JBake documentation [says](https://jbake.org/docs/2.6.7/#bake_command):

> "The -b option without any parameters will assume your source content is in the current working directory and will place the baked output into a directory named output in the current directory:"

I don't think the [FIXME](https://github.com/lefou/mill-jbake/blob/ac0b67f2fb8f619915fdb6065822299f88913200/jbake/src/de/tobiasroeser/mill/jbake/JBakeModule.scala#L100) of the `def jbakeServe(): Command[Unit]` target is the problem. I am assuming that the `def jbake: T[PathRef]` target is setting both the input and output directories. So to solve this I think it is only necessary to [add an `/output` to the `jbake` output path](https://github.com/lefou/mill-jbake/blob/ac0b67f2fb8f619915fdb6065822299f88913200/jbake/src/de/tobiasroeser/mill/jbake/JBakeModule.scala#L92). Note that setting the path in the [server command](https://jbake.org/docs/2.6.7/#server_command) doesn't help because JBake always adds `/output` to the path. Here is an example showing this: 

```
./mill -i site.jbakeRun -s /home/hmf/VSCodeProjects/hashnode-pubs/out/site/
 ```

And here is the output:

 ```
[6/6] site.jbakeRun 
JBake v2.6.7 (2021-05-14 21:54:29[GMT+01:00]) [http://jbake.org]

18:04:16.930 INFO  org.jbake.launcher.BakeWatcher - Watching for (content, template, asset) changes in [/home/hmf/VSCodeProjects/hashnode-pubs/out/site/jbake.dest]
18:04:17.000 INFO  org.jbake.launcher.JettyServer - Serving out contents of: [/home/hmf/VSCodeProjects/hashnode-pubs/out/site/jbake.dest/output] on http://localhost:8820/
18:04:17.000 INFO  org.jbake.launcher.JettyServer - (To stop server hit CTRL-C)
 ```

**Comment by lefou** [comment]
Yes, there is an issue with the output dir, that's why we there is that FIXME. We require most probably a solution specific to the selected JBake version. 

TBH, I'm not exactly sure what you're proposing to solve the issue. Create an `output` dir in the current destination dir?

FTR, here is my Gitter question about this issue: https://gitter.im/jbake-org/jbake?at=5c68865080df6804a1b83744

Unfortunately, there was no response.

**Comment by lefou** [comment]
Here is the relevant PR in JBake repo

* https://github.com/jbake-org/jbake/pull/595

Unfortunately, it's from 2019, yet not merged 🤔

**Comment by lefou** [comment]
From the JBake usage help, you could try to specify to destination directory as a second argument. Can you try that?

**Comment by hmf** [comment]
> TBH, I'm not exactly sure what you're proposing to solve the issue. Create an `output` dir in the current destination dir?

Yes. Exactly that. 

> 
> FTR, here is my Gitter question about this issue: https://gitter.im/jbake-org/jbake?at=5c68865080df6804a1b83744
> 
> Unfortunately, there was no response.

That was what I was afraid of. Hence the suggestion of making the change on this side.

**Comment by hmf** [comment]
> From the JBake usage help, you could try to specify to destination directory as a second argument. Can you try that?

I assume you referring to the "baking"?  As I said above, serving won't work because it always appends the `/output`.  To make serving work, I can set the paths for the "baking". Here is an example: 

```bash
./mill -i site.jbakeRun -b /home/hmf/VSCodeProjects/hashnode-pubs/site/src /home/hmf/VSCodeProjects/hashnode-pubs/out/site/jbake.dest/ouput
```
Note  that I am forced to set `/output` as the destination. This works but is cumbersome because I must determine and define the paths.

**Comment by hmf** [comment]
> Yes, there is an issue with the output dir, that's why we there is that FIXME. We require most probably a solution specific to the selected JBake version.

I was hoping JBake's behavior had not changed. Hence the suggestion "just" to conform to the "server path". I see now this is not quite as simple. 8-(

**Comment by lefou** [comment]
From a short look at the source code of JBake, I think it will use the specified destination directory as a base for serving, but only when it is given explicitly. This requires to specify it somehow. But I lack the time and a useful test project to try that atm.

Could you checkout and patch mill-jbake locally to test your approach? If it works somehow you already have a draft PR, which I can take over.

**Comment by lefou** [comment]
@hmf Can you checkout and test this branch?

* https://github.com/lefou/mill-jbake/tree/fix-serve

Build with:

```
$ mill __.publishLocal
Publishing Artifact(de.tototec,de.tobiasroeser.mill.jbake_mill0.10_2.12,0.2.2-1-35e8f7) to ivy repo /home/lefou/.ivy2/local
```

Then use version `0.2.2-1-35e8f7` in your plugin import.

**Comment by hmf** [comment]
@lefou Tested. Repeated the init, bake and serve. Worked perfectly. 

I looked for the `output` but their is none. The serving output shows:

```
10:19:40.052 INFO  c.o.orient.core.db.OrientDBEmbedded - - shutdown storage: cache...
10:19:40.091 INFO  org.jbake.launcher.BakeWatcher - Watching for (content, template, asset) changes in [/home/hmf/VSCodeProjects/hashnode-pubs/site/src]
10:19:40.141 INFO  org.jbake.launcher.JettyServer - Serving out contents of: [/home/hmf/VSCodeProjects/hashnode-pubs/out/site/jbake.dest] on http://localhost:8820/
10:19:40.141 INFO  org.jbake.launcher.JettyServer - (To stop server hit CTRL-C)
```
I am curious, how did you do that?
EDIT: Ok. Compared the code. You now set source and destination. 

Thank you very much. 
EDIT: If you need additional testing, just say so. Tested with "2.6.7".
