### ISSUE TITLE
Latest release (0.3.0) not in Maven

### ISSUE THREAD

**Issue by hmf** [lefou/mill-jbake#16]
I am assuming once a release appears here, shortly after it will be available in Maven. It has ben quite a few hours since the release and it still not in the Maven repo. I have checked here:

https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.jbake_mill0.10_2.13/

@lefou Just to let you know in case something went wrong. No hurry on this one.

**Comment by lefou** [comment]
Thanks for notifying me. Indeed, the publish tasks didn't run after I renamed the master branch to main but forgot to update the GHA setup. Fixed in #17.

Release should appear soon in Maven Central.

**Comment by hmf** [comment]
@lefou  Just tested. Working. Thank you.
