### ISSUE TITLE
Support Mill 0.10.x (was: Failed to resolve Ivy dependencies)

### ISSUE THREAD

**Issue by hmf** [lefou/mill-jbake#4]
When I execute the following (initial) command:

```
./mill -i resolve _
```

I get:

```
Failed to resolve ivy dependencies:Error downloading de.tototec:de.tobiasroeser.mill.jbake_2.13:0.2.1
  not found: /home/hmf/.ivy2/local/de.tototec/de.tobiasroeser.mill.jbake_2.13/0.2.1/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.jbake_2.13/0.2.1/de.tobiasroeser.mill.jbake_2.13-0.2.1.pom
```

When I look at the Maven repository's URL, indeed I only see:

```
[bake](https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.jbake_2.12/)
```

Do I need to add some specific repo?

TIA

**Comment by hmf** [comment]
Small update. If I force the Scala version to 2.12:

```
import $ivy.`de.tototec:de.tobiasroeser.mill.jbake_2.12:0.2.1`
```

and execute:

```
$ ./millw -i resolve _
```

I get the execution error:

```
https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.jbake_2.12/0.2.1/de.tobiasroeser.mill.jbake_2.12-0.2.1.pom
  100,0% [##########] 1,9 KiB (4,0 KiB / s)
https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.jbake_2.12/0.2.1/de.tobiasroeser.mill.jbake_2.12-0.2.1-sources.jar
  100,0% [##########] 9,4 KiB (36,5 KiB / s)
Compiling /home/hmf/VSCodeProjects/hashnode-pubs/build.sc
[1/1] resolve 
1 targets failed
resolve java.lang.reflect.InvocationTargetException
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    mill.define.Module$Internal.$anonfun$reflect$4(Module.scala:70)
    scala.collection.ArrayOps$WithFilter.map(ArrayOps.scala:90)
    mill.define.Module$Internal.reflect(Module.scala:62)
    mill.define.Module$Internal.reflectAll(Module.scala:73)
    mill.define.Module$Internal.reflectNestedObjects(Module.scala:81)
    mill.define.Module.millModuleDirectChildren$lzycompute(Module.scala:25)
    mill.define.Module.millModuleDirectChildren(Module.scala:25)
    mill.main.ResolveMetadata$.singleModuleMeta(Resolve.scala:13)
    mill.main.ResolveMetadata$.direct$1(Resolve.scala:37)
    mill.main.ResolveMetadata$.endResolveLabel(Resolve.scala:44)
    mill.main.Resolve.resolve(Resolve.scala:417)
    mill.main.RunScript$.$anonfun$resolveTasks$7(RunScript.scala:249)
    scala.util.Either.map(Either.scala:382)
    mill.main.RunScript$.$anonfun$resolveTasks$6(RunScript.scala:233)
    scala.collection.immutable.List.map(List.scala:246)
    scala.collection.immutable.List.map(List.scala:79)
    mill.main.RunScript$.$anonfun$resolveTasks$5(RunScript.scala:232)
    scala.util.Either.flatMap(Either.scala:352)
    mill.main.RunScript$.resolveTasks(RunScript.scala:229)
    mill.main.RunScript$.$anonfun$resolveTasks$2(RunScript.scala:202)
    scala.collection.immutable.List.map(List.scala:246)
    scala.collection.immutable.List.map(List.scala:79)
    mill.main.RunScript$.$anonfun$resolveTasks$1(RunScript.scala:201)
    scala.util.Either.flatMap(Either.scala:352)
    mill.main.RunScript$.resolveTasks(RunScript.scala:200)
    mill.main.MainModule.$anonfun$resolve$1(MainModule.scala:105)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce
    ammonite.$file.build$.site$lzycompute$1(build.sc:41)
    ammonite.$file.build$.site(build.sc:41)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    mill.define.Module$Internal.$anonfun$reflect$4(Module.scala:70)
    scala.collection.ArrayOps$WithFilter.map(ArrayOps.scala:90)
    mill.define.Module$Internal.reflect(Module.scala:62)
    mill.define.Module$Internal.reflectAll(Module.scala:73)
    mill.define.Module$Internal.reflectNestedObjects(Module.scala:81)
    mill.define.Module.millModuleDirectChildren$lzycompute(Module.scala:25)
    mill.define.Module.millModuleDirectChildren(Module.scala:25)
    mill.main.ResolveMetadata$.singleModuleMeta(Resolve.scala:13)
    mill.main.ResolveMetadata$.direct$1(Resolve.scala:37)
    mill.main.ResolveMetadata$.endResolveLabel(Resolve.scala:44)
    mill.main.Resolve.resolve(Resolve.scala:417)
    mill.main.RunScript$.$anonfun$resolveTasks$7(RunScript.scala:249)
    scala.util.Either.map(Either.scala:382)
    mill.main.RunScript$.$anonfun$resolveTasks$6(RunScript.scala:233)
    scala.collection.immutable.List.map(List.scala:246)
    scala.collection.immutable.List.map(List.scala:79)
    mill.main.RunScript$.$anonfun$resolveTasks$5(RunScript.scala:232)
    scala.util.Either.flatMap(Either.scala:352)
    mill.main.RunScript$.resolveTasks(RunScript.scala:229)
    mill.main.RunScript$.$anonfun$resolveTasks$2(RunScript.scala:202)
    scala.collection.immutable.List.map(List.scala:246)
    scala.collection.immutable.List.map(List.scala:79)
    mill.main.RunScript$.$anonfun$resolveTasks$1(RunScript.scala:201)
    scala.util.Either.flatMap(Either.scala:352)
    mill.main.RunScript$.resolveTasks(RunScript.scala:200)
    mill.main.MainModule.$anonfun$resolve$1(MainModule.scala:105)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce
    java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
    ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:241)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ammonite.$file.build$.site$lzycompute$1(build.sc:41)
    ammonite.$file.build$.site(build.sc:41)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.base/java.lang.reflect.Method.invoke(Method.java:566)
    mill.define.Module$Internal.$anonfun$reflect$4(Module.scala:70)
    scala.collection.ArrayOps$WithFilter.map(ArrayOps.scala:90)
    mill.define.Module$Internal.reflect(Module.scala:62)
    mill.define.Module$Internal.reflectAll(Module.scala:73)
    mill.define.Module$Internal.reflectNestedObjects(Module.scala:81)
    mill.define.Module.millModuleDirectChildren$lzycompute(Module.scala:25)
    mill.define.Module.millModuleDirectChildren(Module.scala:25)
    mill.main.ResolveMetadata$.singleModuleMeta(Resolve.scala:13)
    mill.main.ResolveMetadata$.direct$1(Resolve.scala:37)
    mill.main.ResolveMetadata$.endResolveLabel(Resolve.scala:44)
    mill.main.Resolve.resolve(Resolve.scala:417)
    mill.main.RunScript$.$anonfun$resolveTasks$7(RunScript.scala:249)
    scala.util.Either.map(Either.scala:382)
    mill.main.RunScript$.$anonfun$resolveTasks$6(RunScript.scala:233)
    scala.collection.immutable.List.map(List.scala:246)
    scala.collection.immutable.List.map(List.scala:79)
    mill.main.RunScript$.$anonfun$resolveTasks$5(RunScript.scala:232)
    scala.util.Either.flatMap(Either.scala:352)
    mill.main.RunScript$.resolveTasks(RunScript.scala:229)
    mill.main.RunScript$.$anonfun$resolveTasks$2(RunScript.scala:202)
    scala.collection.immutable.List.map(List.scala:246)
    scala.collection.immutable.List.map(List.scala:79)
    mill.main.RunScript$.$anonfun$resolveTasks$1(RunScript.scala:201)
    scala.util.Either.flatMap(Either.scala:352)
    mill.main.RunScript$.resolveTasks(RunScript.scala:200)
    mill.main.MainModule.$anonfun$resolve$1(MainModule.scala:105)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:380)
```

**Comment by lefou** [comment]
Thanks for reporting this issue. This plugin was not released for newer Mill versions, as I'm currently not using it and there was no demand for it. 

But if you would like to use it, I can update the build to release a version for newer Mill versions.

**Comment by hmf** [comment]
I would appreciate it. I was hoping to generate documentation using only Mill + Java/Scala and JBake seems to be one of the very few Java static site generators. The idea is to facilitate the use of the CI/CD pipeline. Trying to document this setup also. 

I was under the impression that you were using JBake for the Mill site but see you are using https://antora.org/.  Any reason why you made this choice?

Don't know how hard this is, but I will try to make a pull request. If you have any pointers, please tell me.

TIA

**Comment by hmf** [comment]
Updated the libraries and it seems to run the integration test. Test fails however because 
because [the bintray URL has been shutdow](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Need to change this. 

Latest version:

https://github.com/jbake-org/jbake/releases/download/v2.6.7/jbake-2.6.7-bin.zip

**Comment by lefou** [comment]
Yeah, I decided to use antora, as it gives out-of-the box support for multi-version documentation. It's also possible to include more modules from different repos, which might be useful when Mill project grows or we want to consolidate documentation of plugins. The downside, compared to JBake, is, that we can only use Asciidoctor for formatting. JBake is much more flexible there. Also, JBake seens to be easier to customize, e.g. for rss/atom feeds or other content.

I already have some PRs merged and pushed, to support latest Mill and JBake.

kind regards

**Comment by hmf** [comment]
> The downside, compared to JBake, is, that we can only use Asciidoctor for formatting. JBake is much more flexible there. Also, JBake seens to be easier to customize, e.g. for rss/atom feeds or other content.

I will stick to JBake then. 

> I already have some PRs merged and pushed, to support latest Mill and JBake.

Wow, that was fast. I have just completed test with success. Download link

     val url = s"https://github.com/jbake-org/jbake/releases/download/v${jbakeVersion()}/jbake-${jbakeVersion()}-bin.zip"  

is working. I take it then you don't need a pull request from my side. Will wait for the new version and try it out again.

**Comment by lefou** [comment]
I guess, I have to disclose, that I was a contributor to JBake some time ago. So, I might be biased here. ;-)

**Comment by hmf** [comment]
I have put some work into using JBake, so thanks. 

On a different note I see `build.sc` has been changed somewhat. I don't have experience with cross builds so I may not bee seeing things correctly, but, why are the Mill versions at 0.6.x? I tried 0.10.4 and it worked. Is this for compatibility? 

I also see you use the `.mill-version` set to 0.9.10.  Shouldn't this be the same as the version above? Any reason it was not set to the latest and greatest?

BTW, os-lib could be set for 0.8.0 and compiles. Saw some deprecation errors and don't know if it is because of this.

Once again thank you

**Comment by lefou** [comment]
I updated the build incrementally, added cross building, added newer versions, without touching unrelated things. And because we can, why not support older Mill versions for some time. E.g. my own older projects using mill-jbake are probably still on Mill 0.6, so if there is no reason to drop this support, just keep it. The dependency setup could be more sophisticated, yes, but coursier will properly use newer transitive versions, and these are compile-time only versions anyways. To in the end, at runtime, we will run with whatever Mill provides.

About the `.mill-version` files. Please notice, that the tool used to build a Mill plugin is not required to be the same as the target platform. So, bumping the build tool chain is completely unrelated to the support of newer Mill versions. Yes, we could use a newer version here. I was hoping for @scala-steward doing the job for me. 😀

**Comment by lefou** [comment]
Also, if we would use os-lib 0.8 for all cross versions, we risk using too new api which may fail at runtime when used with older Mill versions.

**Comment by lefou** [comment]
With PR #9 we now cross build for all Mill versions from 0.6.0 to latest 0.10.4 (0.10.x).

**Comment by hmf** [comment]
Working. Thank you.
